'abandon'|ละทิ้ง
'ability'|ความสามารถ
'able'|สามารถ
'abortion'|การแท้ง
'about'|เกี่ยวกับ
'above'|ข้างบน
'abroad'|ในต่างประเทศ
'absence'|ขาด
'absolute'|แน่นอน
'absolutely'|อย่างแน่นอน
'absorb'|ซึมซับ
'abuse'|การละเมิด
'academic'|วิชาการ
'accept'|ยอมรับ
'access'|ทางเข้า
'accident'|อุบัติเหตุ
'accompany'|มากับ
'accomplish'|ทำให้สำเร็จ
'according'|ตาม
'account'|บัญชี
'accurate'|ถูกต้อง
'accuse'|กล่าวโทษ
'achieve'|บรรลุ
'achievement'|ความสำเร็จ
'acid'|กรด
'acknowledge'|รับทราบ
'acquire'|ได้รับ
'across'|ข้าม
'act'|การกระทำ
'action'|การกระทำ
'active'|คล่องแคล่ว
'activist'|กิจกรรม
'activity'|กิจกรรม
'actor'|นักแสดงชาย
'actress'|นักแสดงหญิง
'actual'|ที่จริง
'actually'|แท้จริง
'ad'|การโฆษณา
'adapt'|ปรับ
'add'|เพิ่ม
'addition'|การเพิ่ม
'additional'|เพิ่มเติม
'address'|ที่อยู่
'adequate'|เพียงพอ
'adjust'|ปรับ
'adjustment'|การปรับ
'administration'|การบริหาร
'administrator'|ผู้บริหาร
'admire'|ชม
'admission'|การรับเข้า
'admit'|ยอมรับ
'adolescent'|วัยรุ่น
'adopt'|นำมาใช้
'adult'|ผู้ใหญ่
'advance'|ความก้าวหน้า
'advanced'|สูง
'advantage'|ความได้เปรียบ
'adventure'|การผจญภัย
'advertising'|การโฆษณา
'advice'|คำแนะนำ
'advise'|แนะนำ
'adviser'|ที่ปรึกษา
'advocate'|สนับสนุน
'affair'|เรื่อง
'affect'|มีผลต่อ
'afford'|จ่าย
'afraid'|เกรงกลัว
'African'|แอฟริกัน
'AfricanAmerican'|แอฟริกันอเมริกัน
'after'|หลังจาก
'afternoon'|ตอนบ่าย
'again'|อีกครั้ง
'against'|ต่อต้าน
'age'|อายุ
'agency'|หน่วยงาน
'agenda'|ระเบียบวาระการประชุม
'agent'|ตัวแทน
'aggressive'|ก้าวร้าว
'ago'|มาแล้ว
'agree'|ตกลง
'agreement'|ข้อตกลง
'agricultural'|การเกษตร
'ah'|อา
'ahead'|ล่วงหน้า
'aid'|ช่วยเหลือ
'aide'|เสนาธิการ
'AIDS'|เอดส์
'aim'|จุดมุ่งหมาย
'air'|อากาศ
'aircraft'|อากาศยาน
'airline'|สายการบิน
'airport'|สนามบิน
'alarm'|สัญญาณเตือนภัย
'album'|อัลบั้ม
'alcohol'|แอลกอฮอล์
'alive'|มีชีวิตอยู่
'all'|ทั้งหมด
'alliance'|พันธมิตร
'allow'|อนุญาต
'ally'|พันธมิตร
'almost'|เกือบจะ
'alone'|คนเดียว
'along'|ตาม
'already'|แล้ว
'also'|ด้วย
'alter'|แก้ไข
'alternative'|ทางเลือก
'although'|แม้ว่า
'always'|เสมอ
'AM'|AM
'amazing'|น่าอัศจรรย์
'American'|อเมริกัน
'among'|ในหมู่
'amount'|จำนวน
'analysis'|การวิเคราะห์
'analyst'|นักวิเคราะห์
'analyze'|วิเคราะห์
'ancient'|โบราณ
'and'|และ
'anger'|ความโกรธ
'angle'|มุม
'angry'|โกรธ
'animal'|สัตว์
'anniversary'|วันครบรอบ
'announce'|ประกาศ
'annual'|ประจำปี
'another'|อื่น
'answer'|ตอบ
'anticipate'|คาดหวัง
'anxiety'|ความกังวล
'any'|ใด
'anybody'|ใครๆ
'anymore'|อีกต่อไป
'anyone'|ใครๆ
'anything'|สิ่งใด
'anyway'|อย่างไรก็ตาม
'anywhere'|ทุกแห่ง
'apart'|ต่างหาก
'apartment'|อพาร์ทเม้น
'apparent'|เห็นได้ชัด
'apparently'|เด่นชัด
'appeal'|อุทธรณ์
'appear'|ปรากฏ
'appearance'|การปรากฏ
'apple'|แอปเปิ้ล
'application'|ใบสมัคร
'apply'|ใช้
'appoint'|แต่งตั้ง
'appointment'|การแต่งตั้ง
'appreciate'|ซาบซึ้ง
'approach'|เข้าใกล้
'appropriate'|เหมาะสม
'approval'|การอนุมัติ
'approve'|อนุมัติ
'approximately'|ประมาณ
'Arab'|อาหรับ
'architect'|สถาปนิก
'area'|พื้นที่
'argue'|เถียง
'argument'|การโต้เถียง
'arise'|เกิดขึ้น
'arm'|แขน
'armed'|ติดอาวุธ
'army'|กองทัพบก
'around'|รอบ
'arrange'|เตรียมการ
'arrangement'|การจัดการ
'arrest'|จับกุม
'arrival'|การมาถึง
'arrive'|มาถึง
'art'|ศิลปะ
'article'|บทความ
'artist'|ศิลปิน
'artistic'|ศิลปะ
'as'|เช่น
'Asian'|เอเชีย
'aside'|กัน
'ask'|ถาม
'asleep'|นอนหลับ
'aspect'|แง่มุม
'assault'|โจมตี
'assert'|ยืนยัน
'assess'|ประเมินผล
'assessment'|การประเมินผล
'asset'|สินทรัพย์
'assign'|กำหนด
'assignment'|การมอบหมาย
'assist'|ช่วยเหลือ
'assistance'|ความช่วยเหลือ
'assistant'|ผู้ช่วย
'associate'|ภาคี
'association'|สมาคม
'assume'|สมมติ
'assumption'|การสันนิษฐาน
'assure'|รับประกัน
'at'|ที่
'athlete'|นักกีฬา
'athletic'|แข็งแรง
'atmosphere'|บรรยากาศ
'attach'|แนบ
'attack'|โจมตี
'attempt'|พยายาม
'attend'|เข้าประชุม
'attention'|ความสนใจ
'attitude'|ท่าที
'attorney'|อัยการ
'attract'|ดึงดูดใจ
'attractive'|มีเสน่ห์
'attribute'|คุณลักษณะ
'audience'|ผู้ชม
'author'|ผู้เขียน
'authority'|ผู้มีอำนาจ
'auto'|รถยนต์
'available'|ใช้ได้
'average'|เฉลี่ย
'avoid'|หลีกเลี่ยง
'award'|รางวัล
'aware'|ทราบ
'awareness'|ความตระหนัก
'away'|ไป
'awful'|น่ากลัว
'baby'|ทารก
'back'|กลับ
'background'|พื้นหลัง
'bad'|ไม่ดี
'badly'|ไม่ดี
'bag'|ถุง
'bake'|อบ
'balance'|สมดุล
'ball'|ลูกบอล
'ban'|ห้าม
'band'|วงดนตรี
'bank'|ธนาคาร
'bar'|บาร์
'barely'|เพิ่งจะ
'barrel'|บาร์เรล
'barrier'|อุปสรรค
'base'|ฐาน
'baseball'|กีฬาเบสบอล
'basic'|ขั้นพื้นฐาน
'basically'|เป็นพื้น
'basis'|รากฐาน
'basket'|ตะกร้า
'basketball'|บาสเกตบอล
'bathroom'|ห้องอาบน้ำ
'battery'|แบตเตอรี่
'battle'|การต่อสู้
'be'|เป็น
'beach'|ชายหาด
'bean'|ถั่ว
'bear'|หมี
'beat'|ตี
'beautiful'|สวย
'beauty'|ความงาม
'because'|เพราะ
'become'|กลายเป็น
'bed'|เตียง
'bedroom'|ห้องนอน
'beer'|เบียร์
'before'|ก่อน
'begin'|เริ่ม
'beginning'|การเริ่มต้น
'behavior'|พฤติกรรม
'behind'|หลัง
'being'|กำลัง
'belief'|ความเชื่อ
'believe'|เชื่อ
'bell'|กระดิ่ง
'belong'|เป็นของ
'below'|ด้านล่าง
'belt'|เข็มขัด
'bench'|ม้านั่ง
'bend'|โค้ง
'beneath'|ใต้
'benefit'|ประโยชน์
'beside'|ข้าง
'besides'|นอกเหนือจาก
'best'|ดีที่สุด
'bet'|เดิมพัน
'better'|ดีกว่า
'between'|ระหว่าง
'beyond'|เกิน
'Bible'|คัมภีร์ไบเบิล
'big'|ใหญ่
'bike'|จักรยาน
'bill'|บิล
'billion'|พันล้าน
'bind'|ผูก
'biological'|ชีวภาพ
'bird'|นก
'birth'|กำเนิด
'birthday'|วันเกิด
'bit'|บิต
'bite'|กัด
'black'|สีดำ
'blade'|ใบมีด
'blame'|ตำหนิ
'blanket'|ผ้าห่ม
'blind'|ตาบอด
'block'|กลุ่ม
'blood'|เลือด
'blow'|ระเบิด
'blue'|สีน้ำเงิน
'board'|คณะกรรมการ
'boat'|เรือ
'body'|ร่างกาย
'bomb'|วางระเบิด
'bombing'|ระเบิด
'bond'|พันธบัตร
'bone'|กระดูก
'book'|หนังสือ
'boom'|ความเจริญ
'boot'|รองเท้า
'border'|ชายแดน
'born'|โดยกำเนิด
'borrow'|ยืม
'boss'|นาย
'both'|ทั้งสอง
'bother'|ตื๊อ
'bottle'|ขวด
'bottom'|ด้านล่าง
'boundary'|เขตแดน
'bowl'|ขัน
'box'|กล่อง
'boy'|เด็กผู้ชาย
'boyfriend'|แฟน
'brain'|สมอง
'branch'|สาขา
'brand'|ยี่ห้อ
'bread'|ขนมปัง
'break'|หยุด
'breakfast'|อาหารเช้า
'breast'|เต้านม
'breath'|ลมหายใจ
'breathe'|หายใจ
'brick'|อิฐ
'bridge'|สะพาน
'brief'|สั้น
'briefly'|สั้น
'bright'|สดใส
'brilliant'|สุกใส
'bring'|นำมาซึ่ง
'British'|อังกฤษ
'broad'|กว้าง
'broken'|แตก
'brother'|พี่ชาย
'brown'|สีน้ำตาล
'brush'|แปรง
'buck'|เจ้าชู้
'budget'|งบ
'build'|สร้าง
'building'|อาคาร
'bullet'|กระสุน
'bunch'|พวง
'burden'|ภาระ
'burn'|เผา
'bury'|ฝังศพ
'bus'|รถบัส
'business'|ธุรกิจ
'busy'|ไม่ว่าง
'but'|แต่
'butter'|เนย
'button'|ปุ่ม
'buy'|ซื้อ
'buyer'|ผู้ซื้อ
'by'|โดย
'cabin'|กระท่อม
'cabinet'|คณะรัฐมนตรี
'cable'|สายเคเบิล
'cake'|เค้ก
'calculate'|คำนวณ
'call'|โทร
'camera'|กล้อง
'camp'|ค่าย
'campaign'|รณรงค์
'campus'|วิทยาเขต
'can'|สามารถ
'Canadian'|ชาวแคนาดา
'cancer'|โรคมะเร็ง
'candidate'|ผู้สมัคร
'cap'|ฝาครอบ
'capability'|ความสามารถ
'capable'|สามารถ
'capacity'|ความจุ
'capital'|เมืองหลวง
'captain'|กัปตัน
'capture'|การจับกุม
'car'|รถ
'carbon'|คาร์บอน
'card'|บัตร
'care'|การดูแล
'career'|อาชีพ
'careful'|ระมัดระวัง
'carefully'|รอบคอบ
'carrier'|ผู้ให้บริการ
'carry'|พกพา
'case'|กรณี
'cash'|เงินสด
'cast'|โยน
'cat'|แมว
'catch'|จับ
'category'|ประเภท
'Catholic'|คาทอลิก
'cause'|สาเหตุ
'ceiling'|เพดาน
'celebrate'|ฉลอง
'celebration'|งานเฉลิมฉลอง
'celebrity'|ชื่อเสียง
'cell'|เซลล์
'center'|ศูนย์
'central'|ศูนย์กลาง
'century'|ศตวรรษ
'CEO'|ผู้บริหารสูงสุด
'ceremony'|พิธี
'certain'|บาง
'certainly'|อย่างแน่นอน
'chain'|โซ่
'chair'|เก้าอี้
'chairman'|ประธาน
'challenge'|ท้าทาย
'chamber'|ห้อง
'champion'|แชมป์
'championship'|การแข่งขันชิงแชมป์
'chance'|โอกาส
'change'|เปลี่ยนแปลง
'changing'|เปลี่ยนแปลง
'channel'|ช่อง
'chapter'|บท
'character'|ตัวละคร
'characteristic'|ลักษณะเฉพาะ
'characterize'|อธิบายลักษณะ
'charge'|ค่าธรรมเนียม
'charity'|การกุศล
'chart'|แผนภูมิ
'chase'|การไล่ล่า
'cheap'|ถูก
'check'|ตรวจสอบ
'cheek'|แก้ม
'cheese'|ชีส
'chef'|พ่อครัว
'chemical'|สารเคมี
'chest'|หน้าอก
'chicken'|ไก่
'chief'|หัวหน้า
'child'|เด็ก
'childhood'|วัยเด็ก
'Chinese'|ชาวจีน
'chip'|ชิป
'chocolate'|ช็อคโกแลต
'choice'|ทางเลือก
'cholesterol'|คอเลสเตอรอล
'choose'|เลือก
'Christian'|คริสเตียน
'Christmas'|คริสต์มาส
'church'|โบสถ์
'cigarette'|บุหรี่
'circle'|วงกลม
'circumstance'|กรณี
'cite'|อ้างอิง
'citizen'|พลเมือง
'city'|เมือง
'civil'|พลเรือน
'civilian'|พลเรือน
'claim'|ข้อเรียกร้อง
'class'|ชั้น
'classic'|คลาสสิก
'classroom'|ห้องเรียน
'clean'|สะอาด
'clear'|ชัดเจน
'clearly'|อย่างเห็นได้ชัด
'client'|ลูกค้า
'climate'|ภูมิอากาศ
'climb'|ไต่
'clinic'|คลินิก
'clinical'|ทางคลินิก
'clock'|นาฬิกา
'close'|ปิด
'closely'|อย่างใกล้ชิด
'closer'|ใกล้ชิด
'clothes'|เสื้อผ้า
'clothing'|เสื้อผ้า
'cloud'|เมฆ
'club'|สโมสร
'clue'|เงื่อนงำ
'cluster'|กลุ่ม
'coach'|โค้ช
'coal'|ถ่านหิน
'coalition'|รัฐบาลผสม
'coast'|ชายฝั่ง
'coat'|เสื้อโค้ท
'code'|รหัส
'coffee'|กาแฟ
'cognitive'|องค์ความรู้
'cold'|หนาว
'collapse'|ล่มสลาย
'colleague'|เพื่อนร่วมงาน
'collect'|เก็บ
'collection'|ชุด
'collective'|โดยรวม
'college'|วิทยาลัย
'colonial'|โคโลเนียล
'color'|สี
'column'|คอลัมน์
'combination'|การรวมกัน
'combine'|รวมกัน
'come'|มา
'comedy'|ความขบขัน
'comfort'|ความสะดวกสบาย
'comfortable'|สบาย
'command'|คำสั่ง
'commander'|ผู้บังคับบัญชา
'comment'|คิดเห็น
'commercial'|เชิงพาณิชย์
'commission'|คณะกรรมาธิการ
'commit'|ผูกมัด
'commitment'|ความมุ่งมั่น
'committee'|กรรมการ
'common'|ร่วมกัน
'communicate'|สื่อสาร
'communication'|การสื่อสาร
'community'|ชุมชน
'company'|บริษัท
'compare'|เปรียบเทียบ
'comparison'|การเปรียบเทียบ
'compete'|แข่งขัน
'competition'|การแข่งขัน
'competitive'|การแข่งขัน
'competitor'|คู่แข่ง
'complain'|บ่น
'complaint'|การร้องเรียน
'complete'|สมบูรณ์
'completely'|อย่างสมบูรณ์
'complex'|ซับซ้อน
'complicated'|ซับซ้อน
'component'|ส่วนประกอบ
'compose'|แต่ง
'composition'|ส่วนประกอบ
'comprehensive'|ครอบคลุม
'computer'|คอมพิวเตอร์
'concentrate'|ตั้งสมาธิ
'concentration'|สมาธิ
'concept'|แนวคิด
'concern'|กังวล
'concerned'|เกี่ยวข้อง
'concert'|คอนเสิร์ต
'conclude'|เอาเป็นว่า
'conclusion'|ข้อสรุป
'concrete'|คอนกรีต
'condition'|เงื่อนไข
'conduct'|ความประพฤติ
'conference'|การประชุม
'confidence'|ความมั่นใจ
'confident'|มั่นใจ
'confirm'|ยืนยัน
'conflict'|ขัดกัน
'confront'|เผชิญหน้า
'confusion'|ความสับสน
'Congress'|คองเกรส
'congressional'|รัฐสภา
'connect'|ต่อ
'connection'|สัมพันธ์
'consciousness'|สติ
'consensus'|เอกฉันท์
'consequence'|ผลพวง
'conservative'|อนุรักษนิยม
'consider'|พิจารณา
'considerable'|มาก
'consideration'|การพิจารณา
'consist'|ประกอบด้วย
'consistent'|คงเส้นคงวา
'constant'|คงที่
'constantly'|นิจศีล
'constitute'|เป็น
'constitutional'|ตามรัฐธรรมนูญ
'construct'|สร้าง
'construction'|การก่อสร้าง
'consultant'|ผู้ให้คำปรึกษา
'consume'|บริโภค
'consumer'|ผู้บริโภค
'consumption'|การบริโภค
'contact'|ติดต่อ
'contain'|บรรจุ
'container'|ภาชนะ
'contemporary'|ร่วมสมัย
'content'|เนื้อหา
'contest'|การประกวด
'context'|บริบท
'continue'|ต่อ
'continued'|อย่างต่อเนื่อง
'contract'|สัญญา
'contrast'|ความแตกต่าง
'contribute'|สนับสนุน
'contribution'|การสนับสนุน
'control'|ควบคุม
'controversial'|ที่เถียงกัน
'controversy'|การทะเลาะวิวาท
'convention'|การประชุม
'conventional'|ตามธรรมเนียม
'conversation'|การสนทนา
'convert'|แปลง
'conviction'|ความเชื่อมั่น
'convince'|โน้มน้าวใจ
'cook'|ปรุงอาหาร
'cookie'|คุกกี้
'cooking'|การปรุงอาหาร
'cool'|เย็น
'cooperation'|ความร่วมมือ
'cop'|ตำรวจ
'cope'|รับมือ
'copy'|สำเนา
'core'|แกน
'corn'|ข้าวโพด
'corner'|มุม
'corporate'|ขององค์กร
'corporation'|บริษัท
'correct'|แก้ไข
'correspondent'|ผู้สื่อข่าว
'cost'|ราคา
'cotton'|ฝ้าย
'couch'|ที่นอน
'could'|ได้
'council'|สภา
'counselor'|ผู้ให้คำปรึกษา
'count'|นับ
'counter'|เคาน์เตอร์
'country'|ประเทศ
'county'|เขต
'couple'|คู่
'courage'|ความกล้าหาญ
'course'|หลักสูตร
'court'|ศาล
'cousin'|ลูกพี่ลูกน้อง
'cover'|ปก
'coverage'|ความคุ้มครอง
'cow'|วัว
'crack'|ร้าว
'craft'|งานฝีมือ
'crash'|ชน
'crazy'|บ้า
'cream'|ครีม
'create'|สร้าง
'creation'|การสร้าง
'creative'|ความคิดสร้างสรรค์
'creature'|สัตว์
'credit'|เครดิต
'crew'|พวกลูกเรือ
'crime'|อาชญากรรม
'criminal'|อาชญากร
'crisis'|วิกฤติ
'criteria'|เกณฑ์
'critic'|นักวิจารณ์
'critical'|วิกฤติ
'criticism'|คำวิจารณ์
'criticize'|วิจารณ์
'crop'|พืชผล
'cross'|ข้าม
'crowd'|ฝูงชน
'crucial'|สำคัญมาก
'cry'|ร้องไห้
'cultural'|ด้านวัฒนธรรม
'culture'|วัฒนธรรม
'cup'|ถ้วย
'curious'|อยากรู้อยากเห็น
'current'|ปัจจุบัน
'currently'|ปัจจุบัน
'curriculum'|หลักสูตร
'custom'|กำหนดเอง
'customer'|ลูกค้า
'cut'|ตัด
'cycle'|วงจร
'dad'|พ่อ
'daily'|ประจำวัน
'damage'|ความเสียหาย
'dance'|เต้นรำ
'danger'|อันตราย
'dangerous'|เป็นอันตราย
'dare'|กล้า
'dark'|มืด
'darkness'|ความมืด
'data'|ข้อมูล
'date'|วันที่
'daughter'|ลูกสาว
'day'|วัน
'dead'|ตาย
'deal'|จัดการ
'dealer'|เจ้ามือ
'dear'|ที่รัก
'death'|ความตาย
'debate'|อภิปราย
'debt'|หนี้สิน
'decade'|ทศวรรษ
'decide'|ตัดสิน
'decision'|การตัดสิน
'deck'|สำรับ
'declare'|ประกาศ
'decline'|ปฏิเสธ
'decrease'|ลดลง
'deep'|ลึก
'deeply'|ลึก
'deer'|กวาง
'defeat'|ความพ่ายแพ้
'defend'|แก้ต่าง
'defendant'|จำเลย
'defense'|ป้องกัน
'defensive'|เกี่ยวกับการป้องกัน
'deficit'|การขาดดุล
'define'|กำหนด
'definitely'|อย่างแน่นอน
'definition'|คำนิยาม
'degree'|ระดับ
'delay'|ความล่าช้า
'deliver'|ส่งมอบ
'delivery'|การจัดส่ง
'demand'|ความต้องการ
'democracy'|ประชาธิปไตย
'Democrat'|ประชาธิปัตย์
'democratic'|ประชาธิปัตย์
'demonstrate'|สาธิต
'demonstration'|สาธิต
'deny'|ปฏิเสธ
'department'|แผนก
'depend'|ขึ้นอยู่กับ
'dependent'|ขึ้นอยู่กับ
'depending'|ทั้งนี้ขึ้นอยู่กับ
'depict'|พรรณนา
'depression'|พายุดีเปรสชัน
'depth'|ความลึก
'deputy'|รอง
'derive'|ได้รับมา
'describe'|อธิบาย
'description'|ลักษณะ
'desert'|ทะเลทราย
'deserve'|สมน้ำสมเนื้อ
'design'|ออกแบบ
'designer'|นักออกแบบ
'desire'|ปรารถนา
'desk'|เคาน์เตอร์
'desperate'|หมดหวัง
'despite'|แม้จะมี
'destroy'|ทำลาย
'destruction'|การทำลาย
'detail'|รายละเอียด
'detailed'|รายละเอียด
'detect'|ตรวจจับ
'determine'|กำหนด
'develop'|พัฒนา
'developing'|ที่กำลังพัฒนา
'development'|พัฒนาการ
'device'|เครื่อง
'devote'|อุทิศ
'dialogue'|บทสนทนา
'die'|ตาย
'diet'|อาหาร
'differ'|แตกต่าง
'difference'|ข้อแตกต่าง
'different'|ต่าง
'differently'|ต่างกัน
'difficult'|ยาก
'difficulty'|ความยาก
'dig'|ขุด
'digital'|ดิจิตอล
'dimension'|มิติ
'dining'|การรับประทานอาหาร
'dinner'|อาหารเย็น
'direct'|โดยตรง
'direction'|ทิศทาง
'directly'|โดยตรง
'director'|ผู้อำนวยการ
'dirt'|ฝุ่น
'dirty'|สกปรก
'disability'|ความพิการ
'disagree'|ไม่เห็นด้วย
'disappear'|หายไป
'disaster'|ภัยพิบัติ
'discipline'|วินัย
'discourse'|สนทนา
'discover'|ค้นพบ
'discovery'|การค้นพบ
'discrimination'|การแบ่งแยก
'discuss'|สนทนา
'discussion'|การสนทนา
'disease'|โรค
'dish'|จาน
'dismiss'|ยกเลิก
'disorder'|ความไม่เป็นระเบียบ
'display'|แสดง
'dispute'|พิพาท
'distance'|ระยะทาง
'distant'|ไกล
'distinct'|แตกต่าง
'distinction'|ความแตกต่าง
'distinguish'|เห็นความแตกต่าง
'distribute'|กระจาย
'distribution'|การกระจาย
'district'|ตำบล
'diverse'|หลากหลาย
'diversity'|ความหลากหลาย
'divide'|แบ่ง
'division'|แผนก
'divorce'|หย่า
'DNA'|ดีเอ็นเอ
'do'|ทำ
'doctor'|คุณหมอ
'document'|เอกสาร
'dog'|หมา
'domestic'|ในประเทศ
'dominant'|เด่น
'dominate'|ครอบงำ
'door'|ประตู
'double'|สอง
'doubt'|สงสัย
'down'|ลง
'downtown'|ตัวเมือง
'dozen'|โหล
'draft'|ร่าง
'drag'|ลาก
'drama'|ละคร
'dramatic'|น่าทึ่ง
'dramatically'|เป็นคุ้งเป็นแคว
'draw'|วาด
'drawing'|การวาดภาพ
'dream'|ฝัน
'dress'|แต่งตัว
'drink'|ดื่ม
'drive'|ขับรถ
'driver'|คนขับรถ
'drop'|หล่น
'drug'|ยา
'dry'|แห้ง
'due'|ครบกำหนด
'during'|ในระหว่าง
'dust'|ฝุ่น
'duty'|หน้าที่
'each'|แต่ละ
'eager'|กระตือรือร้น
'ear'|หู
'early'|ตอนต้น
'earn'|ได้รับ
'earnings'|รายได้
'earth'|โลก
'ease'|ความสะดวก
'easily'|อย่างง่ายดาย
'east'|ทางทิศตะวันออก
'eastern'|ทางตะวันออก
'easy'|ง่าย
'eat'|กิน
'economic'|ด้านเศรษฐกิจ
'economics'|เศรษฐศาสตร์
'economist'|นักเศรษฐศาสตร์
'economy'|เศรษฐกิจ
'edge'|ขอบ
'edition'|ฉบับ
'editor'|บรรณาธิการ
'educate'|ให้ความรู้
'education'|การศึกษา
'educational'|ทางการศึกษา
'educator'|นักการศึกษา
'effect'|ผล
'effective'|มีประสิทธิภาพ
'effectively'|มีประสิทธิภาพ
'efficiency'|อย่างมีประสิทธิภาพ
'efficient'|ที่มีประสิทธิภาพ
'effort'|ความพยายาม
'egg'|ไข่
'eight'|แปด
'either'|ทั้ง
'elderly'|สูงอายุ
'elect'|รักษาการ
'election'|การเลือกตั้ง
'electric'|ไฟฟ้า
'electricity'|ไฟฟ้า
'electronic'|อิเล็กทรอนิกส์
'element'|ธาตุ
'elementary'|เบื้องต้น
'eliminate'|กำจัด
'elite'|ผู้ลากมากดี
'else'|อื่น
'elsewhere'|ที่อื่นๆ
'email'|อีเมล
'embrace'|โอบกอด
'emerge'|ออกมา
'emergency'|กรณีฉุกเฉิน
'emission'|การส่งออก
'emotion'|อารมณ์
'emotional'|อารมณ์
'emphasis'|ความสำคัญ
'emphasize'|เน้น
'employ'|จ้าง
'employee'|ลูกจ้าง
'employer'|นายจ้าง
'employment'|การจ้าง
'empty'|ว่างเปล่า
'enable'|ทำให้สามารถ
'encounter'|พบ
'encourage'|ส่งเสริม
'end'|ปลาย
'enemy'|ศัตรู
'energy'|พลังงาน
'enforcement'|การบังคับใช้
'engage'|ว่าจ้าง
'engine'|เครื่องยนต์
'engineer'|วิศวกร
'engineering'|วิศวกรรม
'English'|อังกฤษ
'enhance'|เสริม
'enjoy'|สนุก
'enormous'|มหาศาล
'enough'|พอ
'ensure'|ทำให้มั่นใจ
'enter'|เข้าสู่
'enterprise'|องค์กร
'entertainment'|การบันเทิง
'entire'|ทั้งหมด
'entirely'|อย่างสิ้นเชิง
'entrance'|ทางเข้า
'entry'|การเข้า
'environment'|สิ่งแวดล้อม
'environmental'|สิ่งแวดล้อม
'episode'|ตอน
'equal'|เท่ากัน
'equally'|พอๆกัน
'equipment'|อุปกรณ์
'era'|ยุค
'error'|ความผิดพลาด
'escape'|หนี
'especially'|โดยเฉพาะอย่างยิ่ง
'essay'|เรียงความ
'essential'|สำคัญ
'essentially'|เป็นหลัก
'establish'|สร้าง
'establishment'|สถานประกอบการ
'estate'|ที่ดิน
'estimate'|ประมาณการ
'etc'|ฯลฯ
'ethics'|จริยธรรม
'ethnic'|ชาติพันธุ์
'European'|ชาวยุโรป
'evaluate'|ประเมินผล
'evaluation'|การประเมินผล
'even'|แม้
'evening'|ตอนเย็น
'event'|เหตุการณ์
'eventually'|ในที่สุด
'ever'|เคย
'every'|ทุกๆ
'everybody'|ทุกคน
'everyday'|ทุกวัน
'everyone'|ทุกคน
'everything'|ทุกอย่าง
'everywhere'|ทุกที่
'evidence'|หลักฐาน
'evolution'|วิวัฒนาการ
'evolve'|คาย
'exact'|แน่นอน
'exactly'|อย่างแน่นอน
'examination'|การตรวจสอบ
'examine'|ตรวจสอบ
'example'|ตัวอย่าง
'exceed'|เกินกว่า
'excellent'|ยอดเยี่ยม
'except'|ยกเว้น
'exception'|ข้อยกเว้น
'exchange'|แลกเปลี่ยน
'exciting'|น่าตื่นเต้น
'executive'|ฝ่ายบริหาร
'exercise'|การออกกำลังกาย
'exhibit'|จัดแสดง
'exhibition'|งานแสดงนิทรรศการ
'exist'|มีอยู่
'existence'|การดำรงอยู่
'existing'|ที่มีอยู่
'expand'|ขยายตัว
'expansion'|การขยายตัว
'expect'|คาดหวัง
'expectation'|ความคาดหวัง
'expense'|ค่าใช้จ่าย
'expensive'|แพง
'experience'|ประสบการณ์
'experiment'|การทดลอง
'expert'|ผู้เชี่ยวชาญ
'explain'|อธิบาย
'explanation'|คำอธิบาย
'explode'|ระเบิด
'explore'|สำรวจ
'explosion'|การระเบิด
'expose'|เปิดเผย
'exposure'|การเปิดรับ
'express'|ด่วน
'expression'|การแสดงออก
'extend'|ต่ออายุ
'extension'|ส่วนขยาย
'extensive'|กว้างขวาง
'extent'|ขอบเขต
'external'|ภายนอก
'extra'|พิเศษ
'extraordinary'|วิสามัญ
'extreme'|สุดขีด
'extremely'|อย่างมาก
'eye'|ตา
'fabric'|ผ้า
'face'|ใบหน้า
'facility'|สิ่งอำนวยความสะดวก
'fact'|ความจริง
'factor'|ปัจจัย
'factory'|โรงงาน
'faculty'|คณะ
'fade'|จางหาย
'fail'|ล้มเหลว
'failure'|ความล้มเหลว
'fair'|ธรรม
'fairly'|อย่างเป็นธรรม
'faith'|ความเชื่อ
'fall'|ตก
'FALSE'|FALSE
'familiar'|คุ้นเคย
'family'|ครอบครัว
'famous'|มีชื่อเสียง
'fan'|แฟน
'fantasy'|จินตนาการ
'far'|ห่างไกล
'farm'|ฟาร์ม
'farmer'|ชาวนา
'fashion'|แฟชั่น
'fast'|รวดเร็ว
'fat'|อ้วน
'fate'|โชคชะตา
'father'|พ่อ
'fault'|ความผิด
'favor'|ชอบ
'favorite'|ที่ชื่นชอบ
'fear'|กลัว
'feature'|ลักษณะ
'federal'|รัฐบาลกลาง
'fee'|ค่าธรรมเนียม
'feed'|อาหาร
'feel'|รู้สึก
'feeling'|ความรู้สึก
'fellow'|มนุษย์
'female'|หญิง
'fence'|รั้ว
'few'|น้อย
'fewer'|น้อยลง
'fiber'|ไฟเบอร์
'fiction'|เรื่องอ่านเล่น
'field'|สนาม
'fifteen'|สิบห้า
'fifth'|ที่ห้า
'fifty'|ห้าสิบ
'fight'|สู้
'fighter'|นักมวย
'fighting'|ศึก
'figure'|รูป
'file'|ไฟล์
'fill'|ใส่
'film'|ฟิล์ม
'final'|สุดท้าย
'finally'|ในที่สุด
'finance'|การเงิน
'financial'|การเงิน
'find'|หา
'finding'|คำวินิจฉัย
'fine'|ละเอียด
'finger'|นิ้ว
'finish'|เสร็จสิ้น
'fire'|ไฟ
'firm'|บริษัท
'first'|เป็นครั้งแรก
'fish'|ปลา
'fishing'|ประมง
'fit'|พอดี
'fitness'|การออกกำลังกาย
'five'|ห้า
'fix'|แก้ไขปัญหา
'flag'|ธง
'flame'|เปลวไฟ
'flat'|แบน
'flavor'|รส
'flee'|หนี
'flesh'|เนื้อ
'flight'|เที่ยวบิน
'float'|ลอย
'floor'|ชั้น
'flow'|ไหล
'flower'|ดอกไม้
'fly'|บิน
'focus'|โฟกัส
'folk'|พื้นบ้าน
'follow'|ปฏิบัติตาม
'following'|ดังต่อไปนี้
'food'|อาหาร
'foot'|เท้า
'football'|ฟุตบอล
'for'|สำหรับ
'force'|บังคับ
'foreign'|ต่างประเทศ
'forest'|ป่า
'forever'|ตลอดไป
'forget'|ลืม
'form'|ฟอร์ม
'formal'|เป็นทางการ
'formation'|การสร้าง
'former'|อดีต
'formula'|สูตร
'forth'|ออกมา
'fortune'|โชคลาภ
'forward'|ข้างหน้า
'found'|พบ
'foundation'|มูลนิธิ
'founder'|ผู้สร้าง
'four'|สี่
'fourth'|ที่สี่
'frame'|กรอบ
'framework'|กรอบ
'free'|ฟรี
'freedom'|เสรีภาพ
'freeze'|แข็ง
'French'|ฝรั่งเศส
'frequency'|ความถี่
'frequent'|บ่อย
'frequently'|บ่อยๆ
'fresh'|สด
'friend'|เพื่อน
'friendly'|เป็นมิตร
'friendship'|มิตรภาพ
'from'|จาก
'front'|ด้านหน้า
'fruit'|ผลไม้
'frustration'|แห้ว
'fuel'|เชื้อเพลิง
'full'|เต็ม
'fully'|อย่างเต็มที่
'fun'|สนุก
'function'|ฟังก์ชัน
'fund'|กองทุน
'fundamental'|พื้นฐาน
'funding'|การระดมทุน
'funeral'|งานศพ
'funny'|ตลก
'furniture'|เฟอร์นิเจอร์
'furthermore'|นอกจากนี้
'future'|อนาคต
'gain'|ได้รับ
'galaxy'|กาแล็กซี
'gallery'|เฉลียง
'game'|เกม
'gang'|แก๊ง
'gap'|ช่องว่าง
'garage'|โรงรถ
'garden'|สวน
'garlic'|กระเทียม
'gas'|แก๊ส
'gate'|ประตู
'gather'|รวบรวม
'gay'|เกย์
'gaze'|จ้องมอง
'gear'|เกียร์
'gender'|เพศ
'gene'|ยีน
'general'|ทั่วไป
'generally'|โดยทั่วไป
'generate'|ผลิต
'generation'|รุ่น
'genetic'|ทางพันธุกรรม
'gentleman'|สุภาพบุรุษ
'gently'|อย่างอ่อนโยน
'German'|เยอรมัน
'gesture'|เชิง
'get'|ได้รับ
'ghost'|ผี
'giant'|ยักษ์
'gift'|ของขวัญ
'gifted'|มีพรสวรรค์
'girl'|สาว
'girlfriend'|แฟน
'give'|ให้
'given'|รับ
'glad'|ดีใจ
'glance'|เหลือบมอง
'glass'|กระจก
'global'|ทั่วโลก
'glove'|ถุงมือ
'go'|ไป
'goal'|เป้าหมาย
'God'|พระเจ้า
'gold'|ทอง
'golden'|ทอง
'golf'|กอล์ฟ
'good'|ดี
'government'|รัฐบาล
'governor'|ผู้ว่าราชการจังหวัด
'grab'|คว้า
'grade'|เกรด
'gradually'|ค่อยๆ
'graduate'|จบการศึกษา
'grain'|เมล็ดข้าว
'grand'|ยิ่งใหญ่
'grandfather'|คุณปู่
'grandmother'|ยาย
'grant'|อนุญาต
'grass'|หญ้า
'grave'|หลุมฝังศพ
'gray'|สีเทา
'great'|ยิ่งใหญ่
'greatest'|ใหญ่ที่สุด
'green'|สีเขียว
'grocery'|ร้านขายของชำ
'ground'|พื้น
'group'|กลุ่ม
'grow'|เจริญ
'growing'|การเจริญเติบโต
'growth'|การเจริญเติบโต
'guarantee'|รับประกัน
'guard'|ยาม
'guess'|เดา
'guest'|แขก
'guide'|แนะนำ
'guideline'|ข้อแนะนำ
'guilty'|รู้สึกผิด
'gun'|ปืน
'guy'|ผู้ชาย
'habit'|นิสัย
'habitat'|ที่อยู่อาศัย
'hair'|ผม
'half'|ครึ่ง
'hall'|ห้องโถง
'hand'|มือ
'handful'|กำมือ
'handle'|จัดการ
'hang'|แขวน
'happen'|เกิดขึ้น
'happy'|มีความสุข
'hard'|ยาก
'hardly'|แทบจะไม่
'hat'|หมวก
'hate'|เกลียด
'have'|มี
'he'|เขา
'head'|หัว
'headline'|พาดหัว
'headquarters'|สำนักงานใหญ่
'health'|สุขภาพ
'healthy'|แข็งแรง
'hear'|ได้ยิน
'hearing'|การได้ยิน
'heart'|หัวใจ
'heat'|ความร้อน
'heaven'|สวรรค์
'heavily'|หนัก
'heavy'|หนัก
'heel'|ส้น
'height'|ความสูง
'helicopter'|เฮลิคอปเตอร์
'hell'|นรก
'hello'|สวัสดี
'help'|ช่วยด้วย
'helpful'|เป็นประโยชน์
'her'|เธอ
'here'|ที่นี่
'heritage'|มรดก
'hero'|พระเอก
'herself'|ตัวเธอเอง
'hey'|เฮ้
'hi'|สวัสดี
'hide'|ปิดบัง
'high'|สูง
'highlight'|ไฮไลท์
'highly'|อย่างมาก
'highway'|ทางหลวง
'hill'|เนินเขา
'him'|เขา
'himself'|ตัวเขาเอง
'hip'|สะโพก
'hire'|จ้าง
'his'|ของเขา
'historian'|นักประวัติศาสตร์
'historic'|ประวัติศาสตร์
'historical'|ประวัติศาสตร์
'history'|ประวัติศาสตร์
'hit'|ตี
'hold'|ถือ
'hole'|รู
'holiday'|วันหยุด
'holy'|ศักดิ์สิทธิ์
'home'|บ้าน
'homeless'|ไม่มีที่อยู่อาศัย
'honest'|ซื่อสัตย์
'honey'|น้ำผึ้ง
'honor'|เกียรติ
'hope'|หวัง
'horizon'|ขอบฟ้า
'horror'|ความน่ากลัว
'horse'|ม้า
'hospital'|โรงพยาบาล
'host'|เจ้าภาพ
'hot'|ร้อน
'hotel'|โรงแรม
'hour'|ชั่วโมง
'house'|บ้าน
'household'|ครัวเรือน
'housing'|การเคหะ
'how'|อย่างไร
'however'|อย่างไรก็ตาม
'huge'|ใหญ่
'human'|เป็นมนุษย์
'humor'|อารมณ์ขัน
'hundred'|ร้อย
'hungry'|หิว
'hunter'|ผู้ล่า
'hunting'|การล่าสัตว์
'hurt'|ทำให้เจ็บ
'husband'|สามี
'hypothesis'|สมมติฐาน
'I'|ผม
'ice'|น้ำแข็ง
'idea'|ความคิด
'ideal'|ในอุดมคติ
'identification'|บัตรประจำตัว
'identify'|แยกแยะ
'identity'|เอกลักษณ์
'ie'|กล่าวคือ
'if'|ถ้า
'ignore'|ไม่สนใจ
'ill'|ป่วย
'illegal'|ที่ผิดกฎหมาย
'illness'|เจ็บป่วย
'illustrate'|แสดง
'image'|ภาพ
'imagination'|จินตนาการ
'imagine'|จินตนาการ
'immediate'|ทันทีทันใด
'immediately'|ทันที
'immigrant'|ผู้อพยพ
'immigration'|การอพยพ
'impact'|ส่งผลกระทบ
'implement'|การดำเนินการ
'implication'|ความหมาย
'imply'|บ่งบอกถึง
'importance'|ความสำคัญ
'important'|สำคัญ
'impose'|กำหนด
'impossible'|เป็นไปไม่ได้
'impress'|ประทับใจ
'impression'|ความประทับใจ
'impressive'|ประทับใจ
'improve'|ปรับปรุง
'improvement'|การปรับปรุง
'in'|ใน
'incentive'|แรงจูงใจ
'incident'|อุบัติการณ์
'include'|ประกอบด้วย
'including'|รวมไปถึง
'income'|เงินได้
'incorporate'|รวมเข้าด้วยกัน
'increase'|เพิ่ม
'increased'|เพิ่มขึ้น
'increasing'|ที่เพิ่มขึ้น
'increasingly'|ขึ้น
'incredible'|เหลือเชื่อ
'indeed'|จริง
'independence'|ความเป็นอิสระ
'independent'|อิสระ
'index'|ดัชนี
'Indian'|ชาวอินเดีย
'indicate'|แสดง
'indication'|การแสดง
'individual'|รายบุคคล
'industrial'|ด้านอุตสาหกรรม
'industry'|อุตสาหกรรม
'infant'|ทารก
'infection'|การติดเชื้อ
'inflation'|เงินเฟ้อ
'influence'|มีอิทธิพล
'inform'|แจ้ง
'information'|ข้อมูล
'ingredient'|ส่วนผสม
'initial'|แรกเริ่ม
'initially'|ในขั้นต้น
'initiative'|ความคิดริเริ่ม
'injury'|ความเสียหาย
'inner'|ภายใน
'innocent'|ผู้บริสุทธิ์
'inquiry'|การสอบสวน
'inside'|ภายใน
'insight'|ข้อมูลเชิงลึก
'insist'|ยืนยัน
'inspire'|บันดาลใจ
'install'|ติดตั้ง
'instance'|ตัวอย่าง
'instead'|แทน
'institution'|สถาบัน
'institutional'|สถาบัน
'instruction'|คำแนะนำ
'instructor'|อาจารย์ผู้สอน
'instrument'|ตราสาร
'insurance'|ประกันภัย
'intellectual'|ทางปัญญา
'intelligence'|สติปัญญา
'intend'|ตั้งใจ
'intense'|เข้มข้น
'intensity'|ความรุนแรง
'intention'|ความตั้งใจ
'interaction'|ปฏิสัมพันธ์
'interest'|ดอกเบี้ย
'interested'|สนใจ
'interesting'|น่าสนใจ
'internal'|ภายใน
'international'|ระหว่างประเทศ
'Internet'|อินเทอร์เน็ต
'interpret'|ตีความ
'interpretation'|การตีความ
'intervention'|การแทรกแซง
'interview'|สัมภาษณ์
'into'|เข้าไป
'introduce'|แนะนำ
'introduction'|บทนำ
'invasion'|การบุกรุก
'invest'|ลงทุน
'investigate'|สอบสวน
'investigation'|ตรวจสอบ
'investigator'|พนักงานสืบสวน
'investment'|การลงทุน
'investor'|นักลงทุน
'invite'|เชิญ
'involve'|รวมถึง
'involved'|ที่เกี่ยวข้อง
'involvement'|การมีส่วนร่วม
'Iraqi'|เกี่ยวกับอิรัก
'Irish'|ไอริช
'iron'|เหล็ก
'Islamic'|อิสลาม
'island'|เกาะ
'Israeli'|ชาวอิสราเอล
'issue'|ปัญหา
'it'|มัน
'Italian'|อิตาลี
'item'|ชิ้น
'its'|ของมัน
'itself'|ตัวเอง
'jacket'|แจ็คเก็ต
'jail'|คุก
'Japanese'|ญี่ปุ่น
'jet'|เครื่องบินไอพ่น
'Jew'|ชาวยิว
'Jewish'|ชาวยิว
'job'|งาน
'join'|ร่วม
'joint'|ร่วมกัน
'joke'|เรื่องตลก
'journal'|วารสาร
'journalist'|นักข่าว
'journey'|การเดินทาง
'joy'|ความปิติยินดี
'judge'|ผู้พิพากษา
'judgment'|การตัดสิน
'juice'|น้ำผลไม้
'jump'|กระโดด
'junior'|อนุ
'jury'|คณะลูกขุน
'just'|เพียงแค่
'justice'|ความยุติธรรม
'justify'|แสดงให้เห็นถึง
'keep'|เก็บ
'key'|สำคัญ
'kick'|เตะ
'kid'|เด็ก
'kill'|ฆ่า
'killer'|นักฆ่า
'killing'|ที่ฆ่า
'kind'|ชนิด
'king'|กษัตริย์
'kiss'|จูบ
'kitchen'|ครัว
'knee'|เข่า
'knife'|มีด
'knock'|เคาะ
'know'|ทราบ
'knowledge'|ความรู้
'lab'|ห้องปฏิบัติการ
'label'|ฉลาก
'labor'|แรงงาน
'laboratory'|ห้องปฏิบัติการ
'lack'|ไม่มี
'lady'|ผู้หญิง
'lake'|ทะเลสาป
'land'|ที่ดิน
'landscape'|ภูมิประเทศ
'language'|ภาษา
'lap'|ตัก
'large'|ใหญ่
'largely'|ส่วนใหญ่
'last'|สุดท้าย
'late'|สาย
'later'|ต่อมา
'Latin'|ละติน
'latter'|ระยะหลัง
'laugh'|หัวเราะ
'launch'|เปิด
'law'|กฎหมาย
'lawn'|สนามหญ้า
'lawsuit'|คดีความ
'lawyer'|ทนายความ
'lay'|ปู
'layer'|ชั้น
'lead'|นำ
'leader'|ผู้นำ
'leadership'|ความเป็นผู้นำ
'leading'|ชั้นนำ
'leaf'|ใบไม้
'league'|พันธมิตร
'lean'|ยัน
'learn'|เรียน
'learning'|การเรียนรู้
'least'|น้อยที่สุด
'leather'|หนังสัตว์
'leave'|ออกจาก
'left'|ซ้าย
'leg'|ขา
'legacy'|มรดก
'legal'|ถูกกฎหมาย
'legend'|ตำนาน
'legislation'|กฎหมาย
'legitimate'|ถูกกฎหมาย
'lemon'|มะนาว
'length'|ความยาว
'less'|น้อยกว่า
'lesson'|บทเรียน
'let'|ปล่อย
'letter'|จดหมาย
'level'|ชั้น
'liberal'|ใจกว้าง
'library'|ห้องสมุด
'license'|อนุญาต
'lie'|โกหก
'life'|ชีวิต
'lifestyle'|วิถีการดำเนินชีวิต
'lifetime'|ตลอดชีวิต
'lift'|ยก
'light'|เบา
'like'|ชอบ
'likely'|น่าจะ
'limit'|จำกัด
'limitation'|การ จำกัด
'limited'|ถูก จำกัด
'line'|เส้น
'link'|ลิงค์
'lip'|ฝีปาก
'list'|รายการ
'listen'|ฟัง
'literally'|อย่างแท้จริง
'literary'|ทางวรรณคดี
'literature'|วรรณกรรม
'little'|น้อย
'live'|มีชีวิต
'living'|การดำรงชีวิต
'load'|ภาระ
'loan'|เงินกู้
'local'|ในประเทศ
'locate'|ตั้งอยู่
'location'|ที่ตั้ง
'lock'|ล็อค
'long'|ยาว
'longterm'|ระยะยาว
'look'|ดู
'loose'|หลวม
'lose'|สูญเสีย
'loss'|การสูญเสีย
'lost'|สูญหาย
'lot'|จำนวนมาก
'lots'|จำนวนมาก
'loud'|ดัง
'love'|ความรัก
'lovely'|น่ารัก
'lover'|คนรัก
'low'|ต่ำ
'lower'|ลดลง
'luck'|โชค
'lucky'|โชคดี
'lunch'|อาหารกลางวัน
'lung'|ปอด
'machine'|เครื่อง
'mad'|บ้า
'magazine'|นิตยสาร
'mail'|อีเมล
'main'|หลัก
'mainly'|ส่วนใหญ่
'maintain'|เก็บรักษา
'maintenance'|ซ่อมบำรุง
'major'|สำคัญ
'majority'|ส่วนใหญ่
'make'|ทำ
'maker'|ผู้สร้าง
'makeup'|แต่งหน้า
'male'|ชาย
'mall'|ห้างสรรพสินค้า
'man'|ชาย
'manage'|จัดการ
'management'|การจัดการ
'manager'|ผู้จัดการ
'manner'|ลักษณะ
'manufacturer'|ผู้ผลิต
'manufacturing'|การผลิต
'many'|จำนวนมาก
'map'|แผนที่
'margin'|ขอบ
'mark'|เครื่องหมาย
'market'|ตลาด
'marketing'|การตลาด
'marriage'|การแต่งงาน
'married'|แต่งงาน
'marry'|แต่งงาน
'mask'|หน้ากาก
'mass'|มวล
'massive'|มาก
'master'|เจ้านาย
'match'|การจับคู่
'material'|วัสดุ
'math'|คณิตศาสตร์
'matter'|เรื่อง
'may'|อาจ
'maybe'|อาจจะ
'mayor'|นายกเทศมนตรี
'me'|ผม
'meal'|อาหาร
'mean'|หมายความ
'meaning'|ความหมาย
'meanwhile'|ในขณะเดียวกัน
'measure'|วัด
'measurement'|การวัด
'meat'|เนื้อ
'mechanism'|กลไก
'media'|สื่อ
'medical'|ทางการแพทย์
'medication'|ยา
'medicine'|ยา
'medium'|กลาง
'meet'|พบกัน
'meeting'|การประชุม
'member'|สมาชิก
'membership'|การเป็นสมาชิก
'memory'|หน่วยความจำ
'mental'|ทางใจ
'mention'|กล่าวถึง
'menu'|เมนู
'mere'|เท่านั้น
'merely'|แค่
'mess'|ความยุ่งเหยิง
'message'|ข่าวสาร
'metal'|โลหะ
'meter'|เมตร
'method'|วิธี
'Mexican'|เม็กซิกัน
'middle'|กลาง
'might'|อาจ
'military'|ทหาร
'milk'|นม
'million'|ล้าน
'mind'|ใจ
'mine'|เหมือง
'minister'|รัฐมนตรี
'minor'|ผู้เยาว์
'minority'|ชนกลุ่มน้อย
'minute'|นาที
'miracle'|ปาฏิหาริย์
'mirror'|กระจกเงา
'miss'|นางสาว
'missile'|ขีปนาวุธ
'mission'|หน้าที่
'mistake'|ผิดพลาด
'mix'|ผสม
'mixture'|สารผสม
'hmm'|อืมมมม
'mode'|โหมด
'model'|แบบ
'moderate'|ปานกลาง
'modern'|ทันสมัย
'modest'|เจียมเนื้อเจียมตัว
'mom'|แม่
'moment'|ขณะ
'money'|เงิน
'monitor'|หน้าจอ
'month'|เดือน
'mood'|อารมณ์
'moon'|ดวงจันทร์
'moral'|คุณธรรม
'more'|มากกว่า
'moreover'|ยิ่งไปกว่านั้น
'morning'|ตอนเช้า
'mortgage'|จำนอง
'most'|มากที่สุด
'mostly'|ส่วนใหญ่
'mother'|แม่
'motion'|การเคลื่อนไหว
'motivation'|แรงจูงใจ
'motor'|เครื่องยนต์
'mount'|ภูเขา
'mountain'|ภูเขา
'mouse'|เม้าส์
'mouth'|ปาก
'move'|ย้าย
'movement'|การเคลื่อนไหว
'movie'|หนัง
'Mr'|นาย
'Mrs'|นาง
'Ms'|นางสาว
'much'|มาก
'multiple'|หลายอย่าง
'murder'|ฆาตกรรม
'muscle'|กล้ามเนื้อ
'museum'|พิพิธภัณฑ์
'music'|เพลง
'musical'|ดนตรี
'musician'|นักดนตรี
'Muslim'|มุสลิม
'must'|ต้อง
'mutual'|ซึ่งกันและกัน
'my'|ของฉัน
'myself'|ตนเอง
'mystery'|ความลึกลับ
'myth'|ตำนาน
'naked'|เปลือยกาย
'name'|ชื่อ
'narrative'|การเล่าเรื่อง
'narrow'|แคบ
'nation'|ประเทศชาติ
'national'|แห่งชาติ
'native'|พื้นเมือง
'natural'|โดยธรรมชาติ
'naturally'|เป็นธรรมชาติ
'nature'|ธรรมชาติ
'near'|ใกล้
'nearby'|ใกล้เคียง
'nearly'|เกือบ
'necessarily'|จำเป็นต้อง
'necessary'|จำเป็น
'neck'|คอ
'need'|จำเป็นต้อง
'negative'|เชิงลบ
'negotiate'|ต่อรอง
'negotiation'|การเจรจาต่อรอง
'neighbor'|เพื่อนบ้าน
'neighborhood'|ย่าน
'neither'|ค่า
'nerve'|เส้นประสาท
'nervous'|หงุดหงิด
'net'|สุทธิ
'network'|เครือข่าย
'never'|ไม่เคย
'nevertheless'|แต่
'new'|ใหม่
'newly'|ใหม่
'news'|ข่าว
'newspaper'|หนังสือพิมพ์
'next'|ต่อไป
'nice'|ดี
'night'|กลางคืน
'nine'|เก้า
'no'|ไม่
'nobody'|ไม่มีใคร
'nod'|พยักหน้า
'noise'|สัญญาณรบกวน
'nomination'|การเสนอชื่อ
'none'|ไม่มี
'nonetheless'|กระนั้น
'nor'|ไม่
'normal'|ปกติ
'normally'|ปกติ
'north'|ทางทิศเหนือ
'northern'|ภาคเหนือ
'nose'|จมูก
'not'|ไม่
'note'|บันทึก
'nothing'|ไม่มีอะไร
'notice'|แจ้งให้ทราบ
'notion'|ความคิด
'novel'|นวนิยาย
'now'|ตอนนี้
'nowhere'|ไม่มีที่ไหนเลย
'not'|ไม่
'nuclear'|นิวเคลียร์
'number'|จำนวน
'numerous'|มากมาย
'nurse'|พยาบาล
'nut'|ถั่ว
'object'|วัตถุ
'objective'|วัตถุประสงค์
'obligation'|ภาระผูกพัน
'observation'|การสังเกต
'observe'|สังเกต
'observer'|ผู้สังเกตการณ์
'obtain'|ได้รับ
'obvious'|ชัดเจน
'obviously'|อย่างชัดเจน
'occasion'|โอกาส
'occasionally'|เป็นครั้งคราว
'occupation'|อาชีพ
'occupy'|ครอบครอง
'occur'|เกิดขึ้น
'ocean'|มหาสมุทร
'odd'|แปลก
'odds'|อัตราต่อรอง
'of'|ของ
'off'|ปิด
'offense'|การกระทำผิดกฎหมาย
'offensive'|น่ารังเกียจ
'offer'|เสนอ
'office'|สำนักงาน
'officer'|เจ้าหน้าที่
'official'|เป็นทางการ
'often'|บ่อยครั้ง
'oh'|โอ้
'oil'|น้ำมัน
'ok'|ตกลง
'okay'|ถูก
'old'|เก่า
'Olympic'|โอลิมปิค
'on'|บน
'once'|ครั้งหนึ่ง
'one'|หนึ่ง
'ongoing'|ต่อเนื่อง
'onion'|หัวหอม
'online'|ออนไลน์
'only'|เท่านั้น
'onto'|ไปยัง
'open'|เปิด
'opening'|การเปิด
'operate'|ทำงาน
'operating'|การดำเนินงาน
'operation'|การทำงาน
'operator'|ผู้ประกอบการ
'opinion'|ความคิดเห็น
'opponent'|คู่แข่ง
'opportunity'|โอกาส
'oppose'|ต่อต้าน
'opposite'|ตรงข้าม
'opposition'|ฝ่ายค้าน
'option'|ตัวเลือก
'or'|หรือ
'orange'|ส้ม
'order'|ใบสั่ง
'ordinary'|สามัญ
'organic'|อินทรีย์
'organization'|องค์กร
'organize'|จัดระเบียบ
'orientation'|ปฐมนิเทศ
'origin'|ที่มา
'original'|เป็นต้นฉบับ
'originally'|แต่เดิม
'other'|อื่นๆ
'others'|คนอื่นๆ
'otherwise'|มิฉะนั้น
'ought'|ควร
'our'|ของเรา
'ourselves'|ตัวเรา
'out'|ออก
'outcome'|ผล
'outside'|ด้านนอก
'oven'|เตาอบ
'over'|เกิน
'overall'|ทั้งหมด
'overcome'|เอาชนะ
'overlook'|มองข้าม
'owe'|เป็นหนี้
'own'|ด้วยตัวเอง
'owner'|เจ้าของ
'pace'|ก้าว
'pack'|ซอง
'package'|บรรจุภัณฑ์
'page'|หน้า
'pain'|ความเจ็บปวด
'painful'|เจ็บปวด
'paint'|สี
'painter'|จิตรกร
'painting'|จิตรกรรม
'pair'|คู่
'pale'|ซีด
'Palestinian'|ปาเลสไตน์
'palm'|ปาล์ม
'pan'|กระทะ
'panel'|แผงหน้าปัด
'pant'|หอบ
'paper'|กระดาษ
'parent'|ผู้ปกครอง
'park'|จอด
'parking'|ที่จอดรถ
'part'|ส่วนหนึ่ง
'participant'|ผู้เข้าร่วม
'participate'|มีส่วนร่วม
'participation'|การมีส่วนร่วม
'particular'|โดยเฉพาะ
'particularly'|โดยเฉพาะ
'partly'|เป็นบางส่วน
'partner'|หุ้นส่วน
'partnership'|หุ้นส่วน
'party'|พรรค
'pass'|ผ่านไป
'passage'|ทางเดิน
'passenger'|ผู้โดยสาร
'passion'|ความชอบ
'past'|อดีต
'patch'|ปะ
'path'|เส้นทาง
'patient'|ผู้ป่วย
'pattern'|แบบแผน
'pause'|หยุด
'pay'|จ่ายเงิน
'payment'|การชำระเงิน
'PC'|พีซี
'peace'|ความสงบ
'peak'|จุดสูงสุด
'peer'|มองดู
'penalty'|การลงโทษ
'people'|คน
'pepper'|พริกไทย
'per'|ต่อ
'perceive'|เข้าใจ
'percentage'|ร้อยละ
'perception'|ความเข้าใจ
'perfect'|สมบูรณ์
'perfectly'|อย่างสมบูรณ์
'perform'|ปฏิบัติการ
'performance'|ประสิทธิภาพ
'perhaps'|บางที
'period'|ระยะเวลา
'permanent'|ถาวร
'permission'|การอนุญาต
'permit'|ใบอนุญาต
'person'|คน
'personal'|ส่วนบุคคล
'personality'|บุคลิกภาพ
'personally'|ส่วนตัว
'personnel'|บุคลากร
'perspective'|มุมมอง
'persuade'|ชักชวน
'pet'|สัตว์เลี้ยง
'phase'|ระยะ
'phenomenon'|ปรากฏการณ์
'philosophy'|ปรัชญา
'phone'|โทรศัพท์
'photo'|ภาพถ่าย
'photograph'|ถ่ายภาพ
'photographer'|ช่างภาพ
'phrase'|วลี
'physical'|กายภาพ
'physically'|ทางร่างกาย
'physician'|แพทย์
'piano'|เปียโน
'pick'|เลือก
'picture'|ภาพ
'pie'|พาย
'piece'|ชิ้น
'pile'|กอง
'pilot'|นักบิน
'pine'|ต้นสน
'pink'|สีชมพู
'pipe'|ท่อ
'pitch'|ขว้าง
'place'|สถานที่
'plan'|วางแผน
'plane'|เครื่องบิน
'planet'|ดาวเคราะห์
'planning'|การวางแผน
'plant'|ปลูก
'plastic'|พลาสติก
'plate'|จาน
'platform'|เวที
'play'|เล่น
'player'|ผู้เล่น
'please'|กรุณา
'pleasure'|ความสุข
'plenty'|ความอุดมสมบูรณ์
'plot'|พล็อต
'plus'|บวก
'PM'|PM
'pocket'|กระเป๋าเสื้อ
'poem'|บทกวี
'poet'|กวี
'poetry'|บทกวี
'point'|จุด
'pole'|เสา
'police'|ตำรวจ
'policy'|นโยบาย
'political'|ในทางการเมือง
'politically'|ในทางการเมือง
'politician'|นักการเมือง
'politics'|การเมือง
'poll'|โพลล์
'pollution'|มลพิษ
'pool'|สระ
'poor'|น่าสงสาร
'pop'|ป๊อป
'popular'|เป็นที่นิยม
'population'|ประชากร
'porch'|ระเบียง
'port'|ท่าเรือ
'portion'|ส่วน
'portrait'|ภาพเหมือน
'portray'|วาดภาพ
'pose'|ท่าทาง
'position'|ตำแหน่ง
'positive'|บวก
'possess'|มี
'possibility'|ความเป็นไปได้
'possible'|เป็นไปได้
'possibly'|อาจ
'post'|เสา
'pot'|หม้อ
'potato'|มันฝรั่ง
'potential'|ที่อาจเกิดขึ้น
'potentially'|ที่อาจเกิดขึ้น
'pound'|ปอนด์
'pour'|เท
'poverty'|ความยากจน
'powder'|ผง
'power'|อำนาจ
'powerful'|มีอำนาจ
'practical'|ประยุกต์
'practice'|การปฏิบัติ
'pray'|อธิษฐาน
'prayer'|การอธิษฐาน
'precisely'|แม่นยำ
'predict'|ทำนาย
'prefer'|ชอบ
'preference'|การตั้งค่า
'pregnancy'|การตั้งครรภ์
'pregnant'|ตั้งครรภ์
'preparation'|การจัดเตรียม
'prepare'|เตรียมการ
'prescription'|ใบสั่งยา
'presence'|การมี
'present'|นำเสนอ
'presentation'|การเสนอ
'preserve'|อนุรักษ์
'president'|ประธาน
'presidential'|ประธานาธิบดี
'press'|กด
'pressure'|ความดัน
'pretend'|แกล้งทำ
'pretty'|น่ารัก
'prevent'|ป้องกัน
'previous'|ก่อน
'previously'|ก่อนหน้านี้
'price'|ราคา
'pride'|ความภาคภูมิใจ
'priest'|พระสงฆ์
'primarily'|ส่วนใหญ่
'primary'|ประถม
'prime'|สำคัญ
'principal'|หลัก
'principle'|หลัก
'print'|พิมพ์
'prior'|ก่อน
'priority'|จัดลำดับความสำคัญ
'prison'|คุก
'prisoner'|นักโทษ
'privacy'|ความเป็นส่วนตัว
'private'|เอกชน
'probably'|อาจ
'problem'|ปัญหา
'procedure'|ขั้นตอน
'proceed'|ดำเนิน
'process'|กระบวนการ
'produce'|ก่อ
'producer'|ผู้ผลิต
'product'|สินค้า
'production'|การผลิต
'profession'|อาชีพ
'professional'|มืออาชีพ
'professor'|ศาสตราจารย์
'profile'|ข้อมูลส่วนตัว
'profit'|กำไร
'program'|โครงการ
'progress'|ความคืบหน้า
'project'|โครงการ
'prominent'|โดดเด่น
'promise'|คำมั่นสัญญา
'promote'|ส่งเสริม
'prompt'|รวดเร็ว
'proof'|พิสูจน์
'proper'|เหมาะสม
'properly'|อย่างถูกต้อง
'property'|คุณสมบัติ
'proportion'|สัดส่วน
'proposal'|ข้อเสนอ
'propose'|เสนอ
'proposed'|เสนอ
'prosecutor'|ฝ่ายอัยการ
'prospect'|โอกาส
'protect'|ป้องกัน
'protection'|การป้องกัน
'protein'|โปรตีน
'protest'|ประท้วง
'proud'|ภูมิใจ
'prove'|พิสูจน์
'provide'|ให้
'provider'|ผู้ให้บริการ
'province'|จังหวัด
'provision'|บทบัญญัติ
'psychological'|จิตวิทยา
'psychologist'|นักจิตวิทยา
'psychology'|จิตวิทยา
'public'|สาธารณะ
'publication'|สิ่งพิมพ์
'publicly'|สาธารณชน
'publish'|ประกาศ
'publisher'|สำนักพิมพ์
'pull'|ดึง
'punishment'|การลงโทษ
'purchase'|ซื้อ
'pure'|บริสุทธิ์
'purpose'|วัตถุประสงค์
'pursue'|ไล่ตาม
'push'|ดัน
'put'|ใส่
'qualify'|มีคุณสมบัติ
'quality'|คุณภาพ
'quarter'|ย่าน
'quarterback'|ตำแหน่งกองหลัง
'question'|คำถาม
'quick'|รวดเร็ว
'quickly'|อย่างรวดเร็ว
'quiet'|เงียบ
'quietly'|เงียบๆ
'quit'|เลิก
'quite'|ทีเดียว
'quote'|อ้างอิง
'race'|แข่ง
'racial'|เกี่ยวกับเชื้อชาติ
'radical'|รุนแรง
'radio'|วิทยุ
'rail'|ทางรถไฟ
'rain'|ฝน
'raise'|ยก
'range'|พิสัย
'rank'|ยศ
'rapid'|รวดเร็ว
'rapidly'|อย่างรวดเร็ว
'rare'|หายาก
'rarely'|ไม่ค่อยมี
'rate'|อัตรา
'rather'|ค่อนข้าง
'rating'|อันดับ
'ratio'|อัตราส่วน
'raw'|ดิบ
'reach'|มาถึง
'react'|เกิดปฏิกิริยา
'reaction'|ปฏิกิริยา
'read'|อ่าน
'reader'|ผู้อ่าน
'reading'|การอ่าน
'ready'|พร้อมแล้ว
'real'|จริง
'reality'|ความจริง
'realize'|ตระหนักถึง
'really'|จริงๆ
'reason'|เหตุผล
'reasonable'|เหมาะสม
'recall'|จำ
'receive'|รับ
'recent'|เมื่อเร็วๆนี้
'recently'|เมื่อเร็วๆนี้
'recipe'|สูตรอาหาร
'recognition'|ได้รับการยอมรับ
'recognize'|รับรู้
'recommend'|แนะนำ
'recommendation'|ข้อเสนอแนะ
'record'|บันทึก
'recording'|การบันทึก
'recover'|กู้
'recovery'|การฟื้นตัว
'recruit'|รับสมัคร
'red'|สีแดง
'reduce'|ลด
'reduction'|การลดลง
'refer'|อ้างถึง
'reference'|การอ้างอิง
'reflect'|สะท้อน
'reflection'|การสะท้อน
'reform'|ปฏิรูป
'refugee'|ผู้ลี้ภัย
'refuse'|ปฏิเสธ
'regard'|คำนึงถึง
'regarding'|เกี่ยวกับ
'regardless'|ไม่คำนึงถึง
'regime'|ระบบการปกครอง
'region'|ภูมิภาค
'regional'|ของแคว้น
'register'|การลงทะเบียน
'regular'|ปกติ
'regularly'|สม่ำเสมอ
'regulate'|ควบคุม
'regulation'|การควบคุม
'reinforce'|เสริมสร้าง
'reject'|ปฏิเสธ
'relate'|สัมพันธ์
'relation'|ความสัมพันธ์
'relationship'|ความสัมพันธ์
'relative'|ญาติ
'relatively'|สัมพัทธ์
'relax'|ผ่อนคลาย
'release'|ปล่อย
'relevant'|ที่เกี่ยวข้อง
'relief'|ความโล่งอก
'religion'|ศาสนา
'religious'|เคร่งศาสนา
'rely'|วางใจ
'remain'|ยังคง
'remaining'|ที่เหลืออยู่
'remarkable'|โดดเด่น
'remember'|จำ
'remind'|เตือน
'remote'|ห่างไกล
'remove'|เอาออก
'repeat'|ทำซ้ำ
'repeatedly'|ซ้ำแล้วซ้ำเล่า
'replace'|แทนที่
'reply'|ตอบ
'report'|รายงาน
'reporter'|ผู้สื่อข่าว
'represent'|แทน
'representation'|การแสดง
'representative'|ตัวแทน
'Republican'|รีพับลิกัน
'reputation'|ชื่อเสียง
'request'|ขอร้อง
'require'|จำเป็นต้อง
'requirement'|ความต้องการ
'research'|การวิจัย
'researcher'|นักวิจัย
'resemble'|คล้ายคลึงกับ
'reservation'|การสำรองห้องพัก
'resident'|ผู้อยู่อาศัย
'resist'|ต่อต้าน
'resistance'|ความต้านทาน
'resolution'|ความละเอียด
'resolve'|แก้ไข
'resort'|รีสอร์ท
'resource'|ทรัพยากร
'respect'|เคารพ
'respond'|ตอบสนอง
'respondent'|ตอบ
'response'|คำตอบ
'responsibility'|ความรับผิดชอบ
'responsible'|รับผิดชอบ
'rest'|ส่วนที่เหลือ
'restaurant'|ร้านอาหาร
'restore'|ฟื้นฟู
'restriction'|การ จำกัด
'result'|ผล
'retain'|รักษา
'retire'|เกษียณอายุ
'retirement'|การเกษียณอายุ
'return'|กลับ
'reveal'|เปิดเผย
'revenue'|รายได้
'review'|ทบทวน
'revolution'|การปฏิวัติ
'rhythm'|จังหวะ
'rice'|ข้าว
'rich'|รวย
'rid'|กำจัด
'ride'|นั่ง
'rifle'|ปืนยาว
'right'|ขวา
'ring'|แหวน
'rise'|ลุกขึ้น
'risk'|อันตราย
'river'|แม่น้ำ
'road'|ถนน
'rock'|หิน
'role'|บทบาท
'roll'|ม้วน
'romantic'|โรแมนติก
'roof'|หลังคา
'room'|ห้อง
'root'|ราก
'rope'|เชือก
'rose'|ดอกกุหลาบ
'rough'|ขรุขระ
'roughly'|ลวก
'round'|รอบ
'route'|เส้นทาง
'routine'|กิจวัตรประจำวัน
'row'|แถว
'rub'|ถู
'rule'|กฎ
'run'|วิ่ง
'running'|วิ่ง
'rural'|ชนบท
'rush'|วิ่ง
'Russian'|รัสเซีย
'sacred'|ศักดิ์สิทธิ์
'sad'|เสียใจ
'safe'|ปลอดภัย
'safety'|ความปลอดภัย
'sake'|เหล้าสาเก
'salad'|สลัด
'salary'|เงินเดือน
'sale'|การขาย
'sales'|ขาย
'salt'|เกลือ
'same'|เหมือนกัน
'sample'|ตัวอย่าง
'sanction'|อนุมัติ
'sand'|ทราย
'satellite'|ดาวเทียม
'satisfaction'|ความพอใจ
'satisfy'|พอใจ
'sauce'|ซอส
'save'|ประหยัด
'saving'|ประหยัด
'say'|พูด
'scale'|ขนาด
'scandal'|เรื่องอื้อฉาว
'scared'|กลัว
'scenario'|สถานการณ์
'scene'|ฉาก
'schedule'|ตารางเวลา
'scheme'|โครงการ
'scholar'|นักวิชาการ
'scholarship'|ทุนการศึกษา
'school'|โรงเรียน
'science'|วิทยาศาสตร์
'scientific'|วิทยาศาสตร์
'scientist'|นักวิทยาศาสตร์
'scope'|ขอบเขต
'score'|คะแนน
'scream'|กรีดร้อง
'screen'|จอภาพ
'script'|ต้นฉบับ
'sea'|ทะเล
'search'|ค้นหา
'season'|ฤดู
'seat'|ที่นั่ง
'second'|ที่สอง
'secret'|ลับ
'secretary'|เลขานุการ
'section'|มาตรา
'sector'|ภาค
'secure'|ปลอดภัย
'security'|ความปลอดภัย
'see'|ดู
'seed'|เมล็ดพันธุ์
'seek'|แสวงหา
'seem'|ดูเหมือน
'segment'|ส่วน
'seize'|ยึด
'select'|เลือก
'selection'|การเลือก
'self'|ตนเอง
'sell'|ขาย
'Senate'|วุฒิสภา
'senator'|วุฒิสมาชิก
'send'|ส่ง
'senior'|ระดับอาวุโส
'sense'|ความรู้สึก
'sensitive'|รู้สึกไว
'sentence'|ประโยค
'separate'|แยก
'sequence'|ลำดับ
'series'|ชุด
'serious'|จริงจัง
'seriously'|อย่างจริงจัง
'serve'|บริการ
'service'|บริการ
'session'|เซสชั่น
'set'|ชุด
'setting'|การตั้งค่า
'settle'|ชำระ
'settlement'|การตั้งถิ่นฐาน
'seven'|เจ็ด
'several'|หลาย
'severe'|รุนแรง
'sex'|เพศ
'sexual'|ทางเพศ
'shade'|ร่มเงา
'shadow'|เงา
'shake'|เขย่า
'shall'|จะต้อง
'shape'|รูปร่าง
'share'|หุ้น
'sharp'|คม
'she'|เธอ
'sheet'|แผ่น
'shelf'|หิ้ง
'shell'|เปลือก
'shelter'|ที่พักอาศัย
'shift'|เปลี่ยน
'shine'|เปล่งปลั่ง
'ship'|เรือ
'shirt'|เสื้อเชิ้ต
'shit'|อึ
'shock'|ช็อก
'shoe'|รองเท้า
'shoot'|ยิง
'shooting'|การยิง
'shop'|ร้านขายของ
'shopping'|ช้อปปิ้ง
'shore'|ฝั่งทะเล
'short'|สั้น
'shortly'|ในไม่ช้า
'shot'|การถ่ายภาพ
'should'|น่า
'shoulder'|ไหล่
'shout'|เสียงร้อง
'show'|แสดง
'shower'|ฝักบัว
'shrug'|ยัก
'shut'|ปิด
'sick'|ป่วย
'side'|ด้าน
'sigh'|ถอนหายใจ
'sight'|สายตา
'sign'|สัญญาณ
'signal'|สัญญาณ
'significance'|ความสำคัญ
'significant'|สำคัญ
'significantly'|อย่างมีความหมาย
'silence'|ความเงียบ
'silent'|เงียบ
'silver'|เงิน
'similar'|คล้ายคลึงกัน
'similarly'|เหมือนกับ
'simple'|ง่าย
'simply'|ง่ายดาย
'sin'|บาป
'since'|ตั้งแต่
'sing'|ร้องเพลง
'singer'|นักร้อง
'single'|เดียว
'sink'|จม
'sir'|ท่าน
'sister'|น้องสาว
'sit'|นั่ง
'site'|เว็บไซต์
'situation'|สถานการณ์
'six'|หก
'size'|ขนาด
'ski'|สกี
'skill'|ความสามารถ
'skin'|ผิว
'sky'|ท้องฟ้า
'slave'|ทาส
'sleep'|นอน
'slice'|ชิ้น
'slide'|สไลด์
'slight'|เล็กน้อย
'slightly'|เล็กน้อย
'slip'|ลื่น
'slow'|ช้า
'slowly'|ช้า
'small'|เล็ก
'smart'|ฉลาด
'smell'|กลิ่น
'smile'|ยิ้ม
'smoke'|ควัน
'smooth'|เรียบ
'snap'|ตะครุบ
'snow'|หิมะ
'so'|ดังนั้น
'socalled'|ที่เรียกว่า
'soccer'|ฟุตบอล
'social'|สังคม
'society'|สังคม
'soft'|อ่อนนุ่ม
'software'|ซอฟต์แวร์
'soil'|ดิน
'solar'|แสงอาทิตย์
'soldier'|ทหาร
'solid'|ของแข็ง
'solution'|วิธีการแก้
'solve'|แก้
'some'|บาง
'somebody'|บางคน
'somehow'|อย่างใด
'someone'|บางคน
'something'|บางสิ่งบางอย่าง
'sometimes'|บางครั้ง
'somewhat'|ค่อนข้าง
'somewhere'|ที่ไหนสักแห่ง
'son'|บุตรชาย
'song'|เพลง
'soon'|ในไม่ช้า
'sophisticated'|ซับซ้อน
'sorry'|ขอโทษ
'sort'|ประเภท
'soul'|จิตวิญญาณ
'sound'|เสียง
'soup'|ซุป
'source'|แหล่ง
'south'|ทางทิศใต้
'southern'|ทางใต้
'Soviet'|โซเวียต
'space'|ช่องว่าง
'Spanish'|สเปน
'speak'|พูด
'speaker'|ผู้พูด
'special'|พิเศษ
'specialist'|ผู้เชี่ยวชาญ
'species'|สายพันธุ์
'specific'|โดยเฉพาะ
'specifically'|เฉพาะ
'speech'|การพูด
'speed'|ความเร็ว
'spend'|ใช้จ่าย
'spending'|การใช้จ่าย
'spin'|ปั่น
'spirit'|วิญญาณ
'spiritual'|มโนมัย
'split'|แยก
'spokesman'|โฆษก
'sport'|กีฬา
'spot'|จุด
'spread'|กระจาย
'spring'|ฤดูใบไม้ผลิ
'square'|สี่เหลี่ยม
'squeeze'|บีบ
'stability'|ความมั่นคง
'stable'|มีเสถียรภาพ
'staff'|บุคลากร
'stage'|เวที
'stair'|บันได
'stake'|เดิมพัน
'stand'|ยืน
'standard'|มาตรฐาน
'standing'|จุดยืน
'star'|ดาว
'stare'|จ้อง
'start'|เริ่มต้น
'state'|สถานะ
'statement'|คำแถลง
'station'|สถานี
'statistics'|สถิติ
'status'|สถานะ
'stay'|พักอยู่
'steady'|มั่นคง
'steal'|ขโมย
'steel'|เหล็ก
'step'|ขั้นตอน
'stick'|ติด
'still'|ยังคง
'stir'|กวน
'stock'|หุ้น
'stomach'|กระเพาะอาหาร
'stone'|หิน
'stop'|หยุด
'storage'|การเก็บรักษา
'store'|เก็บ
'storm'|พายุ
'story'|เรื่องราว
'straight'|ตรง
'strange'|แปลก
'stranger'|คนแปลกหน้า
'strategic'|ยุทธศาสตร์
'strategy'|กลยุทธ์
'stream'|กระแส
'street'|ถนน
'strength'|ความแข็งแรง
'strengthen'|เสริมสร้าง
'stress'|ความตึงเครียด
'stretch'|ยืด
'strike'|การนัดหยุดงาน
'string'|เชือก
'strip'|เพิก
'stroke'|ลากเส้น
'strong'|แข็งแรง
'strongly'|เสถียร
'structure'|โครงสร้าง
'struggle'|การต่อสู้
'student'|นักเรียน
'studio'|สตูดิโอ
'study'|ศึกษา
'stuff'|สิ่ง
'stupid'|โง่
'style'|สไตล์
'subject'|เรื่อง
'submit'|เสนอ
'subsequent'|ภายหลัง
'substance'|สสาร
'substantial'|รูปธรรม
'succeed'|ประสบความสำเร็จ
'success'|ความสำเร็จ
'successful'|ที่ประสบความสำเร็จ
'successfully'|ประสบความสำเร็จ
'such'|อย่างเช่น
'sudden'|ฉับพลัน
'suddenly'|ทันใดนั้น
'sue'|ฟ้อง
'suffer'|ประสบ
'sufficient'|เพียงพอ
'sugar'|น้ำตาล
'suggest'|แนะนำ
'suggestion'|ข้อเสนอแนะ
'suicide'|การฆ่าตัวตาย
'suit'|สูท
'summer'|ฤดูร้อน
'summit'|ประชุมสุดยอด
'sun'|ดวงอาทิตย์
'super'|ซุปเปอร์
'supply'|จัดหา
'support'|สนับสนุน
'supporter'|ผู้สนับสนุน
'suppose'|สมมติ
'supposed'|ควร
'Supreme'|สูงสุด
'sure'|แน่ใจ
'surely'|อย่างแน่นอน
'surface'|พื้นผิว
'surgery'|ศัลยกรรม
'surprise'|แปลกใจ
'surprised'|ประหลาดใจ
'surprising'|น่าแปลกใจ
'surprisingly'|อย่างแปลกใจ
'surround'|รอบทิศทาง
'survey'|สำรวจ
'survival'|การอยู่รอด
'survive'|อยู่รอด
'survivor'|ผู้รอดชีวิต
'suspect'|สงสัย
'sustain'|ประคับประคอง
'swear'|สาบาน
'sweep'|กวาด
'sweet'|หวาน
'swim'|การว่ายน้ำ
'swing'|แกว่ง
'switch'|สวิตซ์
'symbol'|สัญลักษณ์
'symptom'|อาการ
'system'|ระบบ
'table'|ตาราง
'tablespoon'|ช้อนโต๊ะ
'tactic'|ชั้นเชิง
'tail'|หาง
'take'|เอา
'tale'|นิทาน
'talent'|ความสามารถพิเศษ
'talk'|การพูดคุย
'tall'|สูง
'tank'|ถัง
'tap'|แตะเบาๆ
'tape'|เทป
'target'|เป้า
'task'|งาน
'taste'|ลิ้มรส
'tax'|ภาษี
'taxpayer'|ผู้เสียภาษีอากร
'tea'|ชา
'teach'|สอน
'teacher'|ครู
'teaching'|การสอน
'team'|ทีม
'tear'|ฉีก
'teaspoon'|ช้อนชา
'technical'|วิชาการ
'technique'|เทคนิค
'technology'|เทคโนโลยี
'teen'|วัยรุ่น
'teenager'|วัยโจ๋
'telephone'|โทรศัพท์
'telescope'|กล้องโทรทรรศน์
'television'|โทรทัศน์
'tell'|บอก
'temperature'|อุณหภูมิ
'temporary'|ชั่วคราว
'ten'|สิบ
'tend'|มีแนวโน้ม
'tendency'|ความโน้มเอียง
'tennis'|เทนนิส
'tension'|ความตึงเครียด
'tent'|เต็นท์
'term'|วาระ
'terms'|เงื่อนไข
'terrible'|น่ากลัว
'territory'|อาณาเขต
'terror'|ความหวาดกลัว
'terrorism'|ลัทธิก่อการร้าย
'terrorist'|ผู้ก่อการร้าย
'test'|ทดสอบ
'testify'|เป็นพยาน
'testimony'|พยานหลักฐาน
'testing'|การทดสอบ
'text'|ข้อความ
'than'|กว่า
'thank'|ขอบคุณ
'thanks'|ขอบคุณ
'that'|ที่
'the'|จำพวก
'theater'|โรงละคร
'their'|ของพวกเขา
'them'|พวกเขา
'theme'|กระทู้
'themselves'|ตัวเอง
'then'|แล้วก็
'theory'|ทฤษฎี
'therapy'|การรักษาด้วย
'there'|ที่นั่น
'therefore'|ดังนั้น
'these'|เหล่านี้
'they'|พวกเขา
'thick'|หนา
'thin'|ผอม
'thing'|สิ่ง
'think'|คิด
'thinking'|คิด
'third'|ที่สาม
'thirty'|สามสิบ
'this'|นี้
'those'|เหล่านั้น
'though'|แม้
'thought'|คิดว่า
'thousand'|พัน
'threat'|การคุกคาม
'threaten'|ขู่
'three'|สาม
'throat'|ลำคอ
'through'|ตลอด
'throughout'|ตลอด
'throw'|โยน
'thus'|ดังนั้น
'ticket'|ตั๋ว
'tie'|ผูก
'tight'|แน่น
'time'|เวลา
'tiny'|ขนาดเล็ก
'tip'|ปลาย
'tire'|ยาง
'tired'|เหนื่อย
'tissue'|เนื้อเยื่อ
'title'|หัวข้อ
'to'|ไปยัง
'tobacco'|ยาสูบ
'today'|ในวันนี้
'toe'|นิ้วเท้า
'together'|ด้วยกัน
'tomato'|มะเขือเทศ
'tomorrow'|วันพรุ่งนี้
'tone'|โทน
'tongue'|ลิ้น
'tonight'|คืนนี้
'too'|เกินไป
'tool'|เครื่องมือ
'tooth'|ฟัน
'top'|ด้านบน
'topic'|หัวข้อเรื่อง
'toss'|โยน
'total'|ทั้งหมด
'totally'|โดยสิ้นเชิง
'touch'|แตะ
'tough'|ยาก
'tour'|การท่องเที่ยว
'tourist'|นักท่องเที่ยว
'tournament'|การแข่งขัน
'toward'|ไปทาง
'towards'|ไปทาง
'tower'|หอคอย
'town'|ตัวเมือง
'toy'|ของเล่น
'trace'|ติดตาม
'track'|ลู่
'trade'|ค้า
'tradition'|ประเพณี
'traditional'|แบบดั้งเดิม
'traffic'|การจราจร
'tragedy'|โศกนาฏกรรม
'trail'|ทาง
'train'|รถไฟ
'training'|การอบรม
'transfer'|โอน
'transform'|แปลง
'transformation'|การแปลง
'transition'|การเปลี่ยนแปลง
'translate'|แปลความ
'transportation'|การขนส่ง
'travel'|การท่องเที่ยว
'treat'|รักษา
'treatment'|การรักษา
'treaty'|สนธิสัญญา
'tree'|ต้นไม้
'tremendous'|มหึมา
'trend'|แนวโน้ม
'trial'|การทดลอง
'tribe'|เผ่า
'trick'|เคล็ดลับ
'trip'|การเดินทาง
'troop'|กองร้อย
'trouble'|ปัญหา
'truck'|รถบรรทุก
'TRUE'|TRUE
'truly'|อย่างแท้จริง
'trust'|วางใจ
'truth'|ความจริง
'try'|ลอง
'tube'|หลอด
'tunnel'|อุโมงค์
'turn'|กลับ
'TV'|โทรทัศน์
'twelve'|สิบสอง
'twenty'|ยี่สิบ
'twice'|สองครั้ง
'twin'|คู่
'two'|สอง
'type'|ชนิด
'typical'|ตามแบบฉบับ
'typically'|เป็นปกติ
'ugly'|น่าเกลียด
'ultimate'|ที่สุด
'ultimately'|ในที่สุด
'unable'|ไม่สามารถ
'uncle'|ลุง
'under'|ภายใต้
'undergo'|ได้รับ
'understand'|เข้าใจ
'understanding'|ความเข้าใจ
'unfortunately'|น่าเสียดาย
'uniform'|เหมือนกัน
'union'|สหภาพ
'unique'|เป็นเอกลักษณ์
'unit'|หน่วย
'United'|ปึกแผ่น
'universal'|สากล
'universe'|จักรวาล
'university'|มหาวิทยาลัย
'unknown'|ไม่ทราบ
'unless'|เว้นแต่
'unlike'|แตกต่าง
'unlikely'|ไม่แน่
'until'|จนกระทั่ง
'unusual'|ผิดปกติ
'up'|ขึ้น
'upon'|เมื่อ
'upper'|บน
'urban'|ในเมือง
'urge'|กระตุ้น
'us'|เรา
'use'|ใช้
'used'|มือสอง
'useful'|มีประโยชน์
'user'|ผู้ใช้งาน
'usual'|ตามปกติ
'usually'|มักจะ
'utility'|ประโยชน์
'vacation'|วันหยุด
'valley'|หุบเขา
'valuable'|มีคุณค่า
'value'|ความคุ้มค่า
'variable'|ตัวแปร
'variation'|การเปลี่ยนแปลง
'variety'|ความหลากหลาย
'various'|ต่างๆ
'vary'|แตกต่าง
'vast'|กว้างใหญ่
'vegetable'|ผัก
'vehicle'|พาหนะ
'venture'|เสี่ยง
'version'|รุ่น
'versus'|กับ
'very'|มาก
'vessel'|เรือ
'veteran'|ทหารผ่านศึก
'via'|ผ่านทาง
'victim'|เหยื่อ
'victory'|ชัยชนะ
'video'|วีดีโอ
'view'|ดู
'viewer'|ผู้ชม
'village'|หมู่บ้าน
'violate'|ละเมิด
'violation'|การละเมิด
'violence'|ความรุนแรง
'violent'|รุนแรง
'virtually'|จวน
'virtue'|คุณธรรม
'virus'|ไวรัส
'visible'|มองเห็นได้
'vision'|วิสัยทัศน์
'visit'|เยือน
'visitor'|ผู้มาเยือน
'visual'|ภาพ
'vital'|จำเป็น
'voice'|เสียงพูด
'volume'|ปริมาณ
'volunteer'|อาสาสมัคร
'vote'|โหวต
'voter'|ผู้เลือกตั้ง
'vs'|ต่อสู้กับ
'vulnerable'|อ่อนแอ
'wage'|ค่าจ้าง
'wait'|รอ
'wake'|ปลุก
'walk'|เดิน
'wall'|ผนัง
'wander'|ระเหเร่ร่อน
'want'|ต้องการ
'war'|สงคราม
'warm'|อบอุ่น
'warn'|เตือน
'warning'|การเตือน
'wash'|ล้าง
'waste'|ของเสีย
'watch'|ดู
'water'|น้ำ
'wave'|คลื่น
'way'|ทาง
'we'|เรา
'weak'|อ่อนแอ
'wealth'|ความมั่งคั่ง
'wealthy'|ร่ำรวย
'weapon'|อาวุธ
'wear'|สวมใส่
'weather'|สภาพอากาศ
'wedding'|งานแต่งงาน
'week'|สัปดาห์
'weekend'|สุดสัปดาห์
'weekly'|รายสัปดาห์
'weigh'|ชั่งน้ำหนัก
'weight'|น้ำหนัก
'welcome'|ยินดีต้อนรับ
'welfare'|สวัสดิการ
'well'|ดี
'west'|ทิศตะวันตก
'western'|ตะวันตก
'wet'|เปียก
'what'|อะไร
'whatever'|อะไรก็ตาม
'wheel'|ล้อ
'when'|เมื่อ
'whenever'|เมื่อไรก็ตาม
'where'|ที่ไหน
'whereas'|แต่ทว่า
'whether'|ว่า
'which'|ที่
'while'|ในขณะที่
'whisper'|กระซิบ
'white'|ขาว
'who'|ใคร
'whole'|ทั้งหมด
'whom'|ใคร
'whose'|ใคร
'why'|ทำไม
'wide'|กว้าง
'widely'|อย่างกว้างขวาง
'widespread'|แพร่หลาย
'wife'|ภรรยา
'wild'|ป่า
'will'|จะ
'willing'|เต็มใจ
'win'|ชนะ
'wind'|ลม
'window'|หน้าต่าง
'wine'|ไวน์
'wing'|ปีก
'winner'|ผู้ชนะ
'winter'|ฤดูหนาว
'wipe'|เช็ด
'wire'|ลวด
'wisdom'|ความฉลาด
'wise'|ฉลาด
'wish'|ประสงค์
'with'|กับ
'withdraw'|ถอน
'within'|ภายใน
'without'|ไม่มี
'witness'|พยาน
'woman'|หญิง
'wonder'|น่าแปลกใจ
'wonderful'|ยอดเยี่ยม
'wood'|เนื้อไม้
'wooden'|ทำด้วยไม้
'word'|คำ
'work'|งาน
'worker'|ผู้ปฏิบัติงาน
'working'|การทำงาน
'works'|โรงงาน
'workshop'|โรงงาน
'world'|โลก
'worried'|กลุ้มใจ
'worry'|กังวล
'worth'|คุ้มค่า
'would'|คงจะ
'wound'|บาดแผล
'wrap'|ห่อ
'write'|เขียน
'writer'|นักเขียน
'writing'|การเขียน
'wrong'|ไม่ถูกต้อง
'yard'|ลาน
'yeah'|ใช่
'year'|ปี
'yell'|เสียงโห่ร้อง
'yellow'|สีเหลือง
'yes'|ใช่
'yesterday'|เมื่อวาน
'yet'|ยัง
'yield'|ผล
'you'|คุณ
'young'|หนุ่มสาว
'your'|ของคุณ
'yours'|ของคุณ
'yourself'|ด้วยตัวคุณเอง
'youth'|หนุ่ม
'zone'|โซน